### ISSUE TITLE
 list index out of range error

### ISSUE THREAD

**Issue by davhum** [uschwartz/nucMACC#13]
Hi nucMACC team,

Have another error and was wondering if you could help decipher where this issue could be coming from. Could it perhaps be coming from the gtf file - an entry whose coordinates that are outside boundaries defined elsewhere? 

ERROR ~ Error executing process > 'MNaseQC:TSS_profile_mono'
Caused by:
  Process `MNaseQC:TSS_profile_mono` terminated with an error exit status (1)

 Command executed:

  computeMatrix reference-point -S file1.bw  file2.bw file3.bw file4.bw   -R /mnt/genomes/hg38_gencode_genes.gtf    --referencePoint TSS    -o "computeMatrix2plot_mono.txt.gz"    -b 1500 -a 1500 --smartLabels -p 5

Command exit status:
  1
                                                                                                                            Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/nucMACC/bin/computeMatrix", line 14, in <module>
      main(args)
    File "/opt/conda/envs/nucMACC/lib/python3.8/site-packages/deeptools/computeMatrix.py", line 421, in main
      hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
    File "/opt/conda/envs/nucMACC/lib/python3.8/site-packages/deeptools/heatmapper.py", line 252, in computeMatrix
      res, labels = mapReduce.mapReduce([score_file_list, parameters],
    File "/opt/conda/envs/nucMACC/lib/python3.8/site-packages/deeptools/mapReduce.py", line 85, in mapReduce
      bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
    File "/opt/conda/envs/nucMACC/lib/python3.8/site-packages/deeptoolsintervals/parse.py", line 593, in __init__
      self.parseGTF(fp, line)
    File "/opt/conda/envs/nucMACC/lib/python3.8/site-packages/deeptoolsintervals/parse.py", line 508, in parseGTF
      self.parseGTFexon(cols)
    File "/opt/conda/envs/nucMACC/lib/python3.8/site-packages/deeptoolsintervals/parse.py", line 444, in parseGTFexon
      if name not in self.exons[self.labelIdx]:
  IndexError: list index out of range

**Comment by uschwartz** [comment]
Hi David,

for me it looks like the chromosome names in the GTF file and bowtie-index do not exactly match.
Be aware some annotations use "chr1" others only "1" as chromosome name.

Further Troubleshooting:
-try to load the resulting  bigwig files in IGV and check the nucleosome profiles
-run the workflow without the GTF file (TSS plot is optional) and try to make the TSS plot manually using deeptools and the resulting nucleosome profiles in bigwig format (should already work with the output you already generated with the workflow)

**Comment by davhum** [comment]
Hi,   removing the gtf file allowed QC step to complete. Now have to think of a way to identify which entry/ies in GTF is causing problem. But at least I can move forward. 

Thanks!
